name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache wheelhouse
        uses: actions/cache@v4
        with:
          path: wheelhouse
          key: wheelhouse-${{ runner.os }}-${{ hashFiles('wheelhouse/*.whl') }}
          restore-keys: |
            wheelhouse-${{ runner.os }}-

      - name: Install pytest
        run: pip install pytest

      - name: Install linters
        run: pip install flake8 black isort

      - name: Run linters
        run: |
          flake8 .
          black --check .
          isort --check .

      - name: Run tests
        env:
          PIP_FIND_LINKS: wheelhouse
        run: |
          chmod +x startup.sh
          ./startup.sh pytest -q
